install.packages("tm")
require("tm")
install.packages("ggplot2")
install.packages("devtools")
my.corpus<-Corpus(DirSource("C:/Users/micha/Desktop/Sem 2 Practicals/BIBD/Practical 2/Text Files"))
my.corpus<-tm_map(my.corpus,removeWords,stopwords("english"))
my.tdm<-TermDocumentMatrix(my.corpus)
#inspect(my.tdm)
my.tdm<-DocumentTermMatrix(my.corpus,control=list(weighting=weightTfIdf,stopwords=TRUE))
#inspect(my.tdm)
my.df<-as.data.frame(inspect(my.tdm))
my.df.scale<-scale(my.df)
d<-dist(my.df.scale,method="euclidean")
fit<-hclust(d,method="ward.D")
plot(fit)
